# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171025_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='郭志芃', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_tel',
            field=models.CharField(default='18813040000', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration deadline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='max_reg',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
