# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171031_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_project',
            field=models.BooleanField(default=False),
        ),
    ]
