# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_project_group_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 1, 0, 55, 11, 504667, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone_num',
            field=models.CharField(default=188000000000, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='class_id',
            field=models.CharField(default=42, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='clothes_size',
            field=models.CharField(choices=[('XS', 'XS'), ('M', 'M'), ('S', 'S'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dormitory',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(default='CS', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(default=360602123456781234, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reading_degree',
            field=models.CharField(choices=[('BS', '本科生'), ('MS', '硕士'), ('PhD', '博士')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default=2014000000, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
