# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171101_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 1, 0, 58, 5, 844921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=10, verbose_name='学号'),
        ),
    ]
