# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171101_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 1, 1, 2, 15, 494156, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone_num',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='class_id',
            field=models.CharField(max_length=10, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('XL', 'XL'), ('XS', 'XS'), ('L', 'L'), ('M', 'M')], max_length=2, verbose_name='衣服尺寸'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dormitory',
            field=models.CharField(max_length=20, verbose_name='寝室号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(max_length=20, verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reading_degree',
            field=models.CharField(choices=[('BS', '本科生'), ('MS', '硕士'), ('PhD', '博士')], max_length=3, verbose_name='攻读学位'),
        ),
    ]
