# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20171101_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Shian', max_length=10, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 1, 1, 19, 41, 652933, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('S', 'S'), ('XS', 'XS'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
