# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20171102_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 2, 2, 34, 4, 639640, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('S', 'S'), ('L', 'L'), ('XS', 'XS'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
