# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20171102_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 2, 3, 27, 0, 854741, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clothes_size',
            field=models.CharField(choices=[('XL', 'XL'), ('XS', 'XS'), ('L', 'L'), ('S', 'S'), ('M', 'M')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
