# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20171102_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 2, 4, 36, 9, 577805, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clothes_size',
            field=models.CharField(choices=[('XS', 'XS'), ('XL', 'XL'), ('L', 'L'), ('S', 'S'), ('M', 'M')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
