# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20171102_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.TimeField(default=datetime.datetime(2017, 11, 2, 4, 45, 35, 868997, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clothes_size',
            field=models.CharField(choices=[('L', 'L'), ('XS', 'XS'), ('XL', 'XL'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
