# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20171102_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=10, verbose_name='学号')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.TimeField(default=datetime.datetime(2017, 11, 4, 14, 54, 24, 234174, tzinfo=utc), verbose_name='出生日期')),
                ('reading_degree', models.CharField(choices=[('BS', '本科生'), ('MS', '硕士'), ('PhD', '博士')], max_length=3, verbose_name='攻读学位')),
                ('faculty', models.CharField(max_length=20, verbose_name='院系')),
                ('class_id', models.CharField(max_length=10, verbose_name='班级')),
                ('clothes_size', models.CharField(choices=[('XS', 'XS'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸')),
                ('email', models.EmailField(max_length=254)),
                ('cellphone_num', models.CharField(max_length=11, verbose_name='手机号码')),
                ('dormitory', models.CharField(max_length=20, verbose_name='寝室号码')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cellphone_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clothes_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dormitory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reading_degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
