# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20171104_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 4, 15, 3, 51, 603179, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('XS', 'XS'), ('L', 'L'), ('M', 'M'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
