# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20171104_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_id_num',
            field=models.CharField(default=17, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 4, 15, 58, 29, 569118, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('XS', 'XS'), ('S', 'S'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
