# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20171104_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 4, 16, 22, 7, 525172, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('L', 'L'), ('S', 'S'), ('XL', 'XL'), ('XS', 'XS'), ('M', 'M')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
