# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20171105_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
        migrations.AddField(
            model_name='user',
            name='submit_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 4, 17, 29, 11, 446128, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('S', 'S'), ('L', 'L'), ('XS', 'XS'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
