# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20171105_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 7, 16, 26, 97879, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='郭志芃', max_length=30, verbose_name='紧急联系人姓名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_tel',
            field=models.CharField(default='18813040000', max_length=30, verbose_name='紧急联系人电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 7, 16, 26, 97879, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group_project',
            field=models.BooleanField(default=False, verbose_name='是否为团体项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_reg',
            field=models.IntegerField(default=100, verbose_name='报名人数限制'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_hot',
            field=models.IntegerField(default=0, verbose_name='当前报名人数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=30, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=models.CharField(max_length=200, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 7, 16, 26, 97879, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 7, 16, 26, 97879, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('XS', 'XS'), ('S', 'S'), ('XL', 'XL'), ('L', 'L')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
