# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20171108_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team_creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team_creator_info',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='project',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='team_leader_info',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='teammate',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='teammate_info',
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 51, 20, 371166, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 51, 20, 371166, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 51, 20, 371166, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 15, 51, 20, 371166, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('XL', 'XL'), ('S', 'S'), ('M', 'M'), ('XS', 'XS'), ('L', 'L')], max_length=2, verbose_name='衣服尺寸'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
