# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20171106_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregisterrelationship',
            name='approval_status',
            field=models.CharField(choices=[(('PE',), '审核中'), (('AP',), '已通过'), ('RE', '未通过')], default=('PE',), max_length=10),
        ),
        migrations.AddField(
            model_name='projectregisterrelationship',
            name='grade',
            field=models.CharField(default='完赛', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 7, 33, 34, 212027, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 7, 33, 34, 212027, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 7, 33, 34, 212027, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 7, 33, 34, 212027, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XS', 'XS'), ('S', 'S'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
