# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20171106_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 8, 22, 41, 887037, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 8, 22, 41, 887037, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 8, 22, 41, 887037, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='approval_status',
            field=models.CharField(choices=[('PE', '审核中'), ('AP', '已通过'), ('RE', '未通过')], default='PE', max_length=10, verbose_name='报名审核状态'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='grade',
            field=models.CharField(default='完赛', max_length=100, verbose_name='比赛成绩'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='if_finished',
            field=models.BooleanField(default=False, verbose_name='比赛已结束'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 8, 22, 41, 887037, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('XS', 'XS'), ('XL', 'XL'), ('S', 'S')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
