# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20171106_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='registered_user_info',
            field=models.ManyToManyField(through='backend.ProjectRegisterRelationship', to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='projectregisterrelationship',
            name='user_info',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 9, 43, 24, 42849, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 9, 43, 24, 42849, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 9, 43, 24, 42849, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 9, 43, 24, 42849, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
