# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20171106_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregisterrelationship',
            name='student_id',
            field=models.CharField(default='afd', max_length=10, verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 17, 28, 494848, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 17, 28, 494848, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 17, 28, 494848, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='name',
            field=models.CharField(max_length=10, verbose_name='选手姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 10, 17, 28, 493845, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XS', 'XS'), ('XL', 'XL'), ('S', 'S')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
