# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20171106_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectregisterrelationship',
            old_name='name',
            new_name='register_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 27, 57, 407620, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 27, 57, 407620, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 10, 27, 57, 407620, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 10, 27, 57, 407620, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('XS', 'XS'), ('M', 'M'), ('S', 'S'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
