# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20171106_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='队伍', max_length=128)),
                ('team_min_reg', models.IntegerField(default=1, verbose_name='队伍人数下限')),
                ('team_max_reg', models.IntegerField(default=0, verbose_name='队伍人数上限')),
                ('teammate_num', models.IntegerField(default=1, verbose_name='队伍当前人数')),
                ('approval_status', models.CharField(choices=[('PE', '审核中'), ('AP', '已通过'), ('RE', '未通过')], default='PE', max_length=10, verbose_name='报名审核状态')),
                ('grade', models.CharField(default='比赛尚未结束', max_length=100, verbose_name='比赛成绩')),
                ('if_finished', models.BooleanField(default=False, verbose_name='比赛已结束')),
                ('if_teammate_finally_confirm', models.BooleanField(default=False, verbose_name='已提交队员名单')),
            ],
            options={
                'verbose_name': '团队 Group',
                'verbose_name_plural': '团队 Group',
            },
        ),
        migrations.CreateModel(
            name='GroupProjectRegisterRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_group_name', models.CharField(default='队伍', max_length=10, verbose_name='队伍名')),
                ('registered_project_name', models.CharField(default='项目', max_length=20, verbose_name='项目名称')),
                ('register_datetime', models.DateTimeField(verbose_name='报名时间')),
                ('approval_status', models.CharField(choices=[('PE', '审核中'), ('AP', '已通过'), ('RE', '未通过')], default='PE', max_length=10, verbose_name='报名审核状态')),
                ('grade', models.CharField(default='完赛', max_length=100, verbose_name='比赛成绩')),
                ('if_finished', models.BooleanField(default=False, verbose_name='比赛已结束')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Group')),
            ],
            options={
                'verbose_name': '项目报名表 ProjectRegisterRelationship',
                'verbose_name_plural': '项目报名表 ProjectRegisterRelationship',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Group')),
            ],
            options={
                'verbose_name': '团队报名表 Membership',
                'verbose_name_plural': '团队报名表 Membership',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目 Project', 'verbose_name_plural': '项目 Project'},
        ),
        migrations.AlterModelOptions(
            name='projectregisterrelationship',
            options={'verbose_name': '项目报名表 ProjectRegisterRelationship', 'verbose_name_plural': '项目报名表 ProjectRegisterRelationship'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息表 UserInfo', 'verbose_name_plural': '用户信息表 UserInfo'},
        ),
        migrations.AddField(
            model_name='project',
            name='min_reg',
            field=models.IntegerField(default=0, verbose_name='报名人数/队伍数下限'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_max_reg',
            field=models.IntegerField(default=5, verbose_name='队伍人数上限'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_min_reg',
            field=models.IntegerField(default=1, verbose_name='队伍人数下限'),
        ),
        migrations.AddField(
            model_name='projectregisterrelationship',
            name='registered_project_name',
            field=models.CharField(default='项目', max_length=20, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 59, 4, 881103, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 59, 4, 881604, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_reg',
            field=models.IntegerField(default=100, verbose_name='报名人数/队伍数上限'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_hot',
            field=models.IntegerField(default=0, verbose_name='当前报名人数/队伍数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 59, 4, 881103, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='grade',
            field=models.CharField(default='比赛尚未结束', max_length=100, verbose_name='比赛成绩'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 14, 59, 4, 880602, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('XS', 'XS'), ('L', 'L'), ('S', 'S'), ('M', 'M'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_created_this_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='team_leader_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_info', to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='membership',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='teammate_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='groupprojectregisterrelationship',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
        ),
        migrations.AddField(
            model_name='groupprojectregisterrelationship',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprojectregisterrelationship',
            name='team_leader_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='backend.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
        ),
        migrations.AddField(
            model_name='group',
            name='team_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='team_creator_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator_info', to='backend.UserInfo'),
        ),
    ]
