# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_auto_20171108_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprojectregisterrelationship',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupprojectregisterrelationship',
            name='project',
        ),
        migrations.RemoveField(
            model_name='groupprojectregisterrelationship',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='groupprojectregisterrelationship',
            name='team_leader_info',
        ),
        migrations.AddField(
            model_name='projectregisterrelationship',
            name='if_group_project',
            field=models.BooleanField(default=False, verbose_name='是否为团队项目'),
        ),
        migrations.AddField(
            model_name='projectregisterrelationship',
            name='rank',
            field=models.CharField(default='比赛尚未结束', max_length=5, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 10, 30, 12, 678678, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 10, 30, 12, 678678, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 10, 30, 12, 678678, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 10, 30, 12, 678678, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('XL', 'XL'), ('M', 'M'), ('XS', 'XS'), ('L', 'L')], max_length=2, verbose_name='衣服尺寸'),
        ),
        migrations.DeleteModel(
            name='GroupProjectRegisterRelationship',
        ),
    ]
