# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_auto_20171106_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '团队 Group', 'verbose_name_plural': '团队 Group'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': '团队报名表 Membership', 'verbose_name_plural': '团队报名表 Membership'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目 Project', 'verbose_name_plural': '项目 Project'},
        ),
        migrations.AlterModelOptions(
            name='projectregisterrelationship',
            options={'verbose_name': '项目报名表 ProjectRegisterRelationship', 'verbose_name_plural': '项目报名表 ProjectRegisterRelationship'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息表 UserInfo', 'verbose_name_plural': '用户信息表 UserInfo'},
        ),
        migrations.RenameField(
            model_name='projectregisterrelationship',
            old_name='registed_project_name',
            new_name='registered_project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='min_reg',
            field=models.IntegerField(default=0, verbose_name='报名人数下限'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 16, 59, 12, 246404, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 16, 59, 12, 246404, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_reg',
            field=models.IntegerField(default=100, verbose_name='报名人数上限'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 16, 59, 12, 246404, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 16, 59, 12, 246404, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('L', 'L'), ('S', 'S'), ('XS', 'XS'), ('M', 'M'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
