# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20171113_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='if_group_project',
            field=models.BooleanField(default=True, verbose_name='是否团队项目'),
        ),
        migrations.AddField(
            model_name='group',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 10, 50, 31, 451994, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 10, 50, 31, 451994, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 10, 50, 31, 451994, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 10, 50, 31, 450992, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('M', 'M'), ('XS', 'XS'), ('XL', 'XL'), ('L', 'L'), ('S', 'S')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
