# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20171107_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='队伍', max_length=128),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 9, 59, 22, 131351, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 9, 59, 22, 131351, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_reg',
            field=models.IntegerField(default=100, verbose_name='报名人数/队伍数上限'),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_reg',
            field=models.IntegerField(default=0, verbose_name='报名人数/队伍数下限'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_hot',
            field=models.IntegerField(default=0, verbose_name='当前报名人数/队伍数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 9, 59, 22, 131351, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 7, 9, 59, 22, 131351, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('XS', 'XS'), ('S', 'S'), ('M', 'M')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
