# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 03:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20171107_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='team_creator',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='team_creator_info',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='team_creator_info', to='backend.UserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='team_leader_info',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_info', to='backend.UserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='teammate_info',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_created_this_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 3, 44, 53, 964811, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 3, 44, 53, 964811, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 3, 44, 53, 964811, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 3, 44, 53, 964310, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('XS', 'XS'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
