# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_auto_20171108_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProjectRegisterRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_group_name', models.CharField(default='队伍', max_length=10, verbose_name='队伍名')),
                ('registered_project_name', models.CharField(default='项目', max_length=20, verbose_name='项目名称')),
                ('register_datetime', models.DateTimeField(verbose_name='报名时间')),
                ('approval_status', models.CharField(choices=[('PE', '审核中'), ('AP', '已通过'), ('RE', '未通过')], default='PE', max_length=10, verbose_name='报名审核状态')),
                ('grade', models.CharField(default='完赛', max_length=100, verbose_name='比赛成绩')),
                ('if_finished', models.BooleanField(default=False, verbose_name='比赛已结束')),
            ],
            options={
                'verbose_name': '项目报名表 ProjectRegisterRelationship',
                'verbose_name_plural': '项目报名表 ProjectRegisterRelationship',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_max_reg',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_min_reg',
        ),
        migrations.AddField(
            model_name='group',
            name='approval_status',
            field=models.CharField(choices=[('PE', '审核中'), ('AP', '已通过'), ('RE', '未通过')], default='PE', max_length=10, verbose_name='报名审核状态'),
        ),
        migrations.AddField(
            model_name='group',
            name='grade',
            field=models.CharField(default='完赛', max_length=100, verbose_name='比赛成绩'),
        ),
        migrations.AddField(
            model_name='group',
            name='if_finished',
            field=models.BooleanField(default=False, verbose_name='比赛已结束'),
        ),
        migrations.AddField(
            model_name='group',
            name='if_teammate_finally_confirm',
            field=models.BooleanField(default=False, verbose_name='已提交队员名单'),
        ),
        migrations.AddField(
            model_name='group',
            name='team_creator_info',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='team_creator_info', to='backend.UserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='team_max_reg',
            field=models.IntegerField(default=0, verbose_name='队伍人数上限'),
        ),
        migrations.AddField(
            model_name='group',
            name='team_min_reg',
            field=models.IntegerField(default=0, verbose_name='队伍人数下限'),
        ),
        migrations.AddField(
            model_name='group',
            name='teammate_num',
            field=models.IntegerField(default=1, verbose_name='队伍当前人数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 11, 49, 293255, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 11, 49, 293255, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 11, 49, 293255, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 14, 11, 49, 292255, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('XS', 'XS')], max_length=2, verbose_name='衣服尺寸'),
        ),
        migrations.AddField(
            model_name='groupprojectregisterrelationship',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Group'),
        ),
        migrations.AddField(
            model_name='groupprojectregisterrelationship',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
        ),
        migrations.AddField(
            model_name='groupprojectregisterrelationship',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprojectregisterrelationship',
            name='team_leader_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
        ),
    ]
