# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_auto_20171108_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_max_reg',
            field=models.IntegerField(default=5, verbose_name='队伍人数上限'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_min_reg',
            field=models.IntegerField(default=0, verbose_name='队伍人数下限'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(default='比赛尚未结束', max_length=100, verbose_name='比赛成绩'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 19, 36, 94804, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 19, 36, 94804, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 19, 36, 94804, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='grade',
            field=models.CharField(default='比赛尚未结束', max_length=100, verbose_name='比赛成绩'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 14, 19, 36, 94303, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('L', 'L'), ('XS', 'XS'), ('XL', 'XL'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
