# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_auto_20171113_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_mark', models.CharField(default='轮播图题注', max_length=20, verbose_name='轮播图题注')),
                ('carousel_image', models.ImageField(upload_to='carousel/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 15, 40, 49, 558966, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 15, 40, 49, 558966, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 15, 40, 49, 543340, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 15, 40, 49, 543340, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 15, 40, 49, 543340, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 15, 40, 49, 558966, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 15, 40, 49, 543340, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('XS', 'XS'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('S', 'S')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
