# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_auto_20171116_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOF_name', models.CharField(default='名人堂', max_length=20, verbose_name='名人堂姓名')),
                ('HOF_gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('HOF_selected_year', models.CharField(default='2018', max_length=4, verbose_name='入选年份')),
                ('HOF_class_id', models.CharField(default='计XX', max_length=5, verbose_name='班级')),
                ('HOF_introduction', models.TextField(default='请输入个人简介(300字以内)', max_length=300, verbose_name='个人简介')),
                ('HOF_honor', models.TextField(default='请输入个人荣誉(300字以内)', max_length=300, verbose_name='个人荣誉')),
                ('HOF_image', models.ImageField(upload_to='HallOfFame')),
                ('HOF_upload_time', models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 998077, tzinfo=utc), verbose_name='上传时间')),
                ('if_HOF_active', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': 'Hall of Fame 名人堂',
                'verbose_name_plural': 'Hall of Fame 名人堂',
            },
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carousel 轮播图', 'verbose_name_plural': 'Carousel 轮播图'},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 997576, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 995071, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 996574, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 993066, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 993066, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 993066, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 994069, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 12, 44, 48, 992063, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('XS', 'XS'), ('L', 'L'), ('M', 'M'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
