# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_auto_20171117_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='approval_status',
            field=models.CharField(choices=[('PE', '审核中'), ('AP', '已通过'), ('RE', '未通过')], default='PE', max_length=10, verbose_name='报名审核状态'),
        ),
        migrations.AddField(
            model_name='membership',
            name='project_name',
            field=models.CharField(default='项目', max_length=20, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 355578, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 353576, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='HOF_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 356050, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 354578, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 351569, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 351569, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 351569, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 352573, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='school_team_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 357053, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 4, 11, 39, 351067, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('XL', 'XL'), ('XS', 'XS'), ('S', 'S'), ('L', 'L'), ('M', 'M')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
