# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 04:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_auto_20171120_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolteam',
            old_name='school_team_honor',
            new_name='school_team_member',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 385764, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 383793, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='HOF_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 386768, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 384794, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 382286, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 382286, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 382286, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 383293, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='school_team_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 387304, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 4, 12, 39, 381288, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('XL', 'XL'), ('M', 'M'), ('L', 'L'), ('XS', 'XS')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
