# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_auto_20171120_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='if_finished',
            field=models.BooleanField(default=False, verbose_name='比赛已结束'),
        ),
        migrations.AddField(
            model_name='project',
            name='if_legacy',
            field=models.BooleanField(default=False, verbose_name='是否为历史项目'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 367487, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 365482, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='HOF_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 368491, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 366485, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 363511, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 363511, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 363511, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 364479, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='school_team_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 369493, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 22, 10, 55, 42, 362507, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('XS', 'XS'), ('XL', 'XL'), ('L', 'L')], max_length=2, verbose_name='衣服尺寸'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='Groupchat@mails.com', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_card',
            field=models.CharField(max_length=30, verbose_name='身份证号\\护照号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
