# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_auto_20171122_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='if_finished',
            field=models.BooleanField(default=False, verbose_name='比赛是否已结束'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='HOF_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='school_team_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 22, 14, 41, 53, 991896, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('S', 'S'), ('XS', 'XS'), ('L', 'L'), ('M', 'M'), ('XL', 'XL')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
