# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_auto_20171122_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_open_id',
            field=models.CharField(default='微信号', max_length=50, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 350111, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 348106, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='HOF_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 351114, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 349109, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ddl_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 346101, tzinfo=utc), verbose_name='报名截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='match_data_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 346101, tzinfo=utc), verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 346101, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='projectregisterrelationship',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 347103, tzinfo=utc), verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='school_team_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 351616, tzinfo=utc), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 2, 6, 39, 41, 345599, tzinfo=utc), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clothes_size',
            field=models.CharField(choices=[('XL', 'XL'), ('M', 'M'), ('XS', 'XS'), ('S', 'S'), ('L', 'L')], max_length=2, verbose_name='衣服尺寸'),
        ),
    ]
